<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class AddressListsAddressListDeleteBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * All 'address_list[]' params are mutually exclusive, only one can be provided.
     *
     * @var AddressListLookup
     */
    protected $addressList;

    /**
     * All 'address_list[]' params are mutually exclusive, only one can be provided.
     */
    public function getAddressList(): AddressListLookup
    {
        return $this->addressList;
    }

    /**
     * All 'address_list[]' params are mutually exclusive, only one can be provided.
     */
    public function setAddressList(AddressListLookup $addressList): self
    {
        $this->initialized['addressList'] = true;
        $this->addressList = $addressList;

        return $this;
    }
}
