<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class CountriesCountryCountryStatesGetResponse200 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var PaginationObject
     */
    protected $pagination;
    /**
     * The list of country states for the given country.
     *
     * @var list<GetCountryCountryStates200ResponseCountryStates>
     */
    protected $countryStates;

    public function getPagination(): PaginationObject
    {
        return $this->pagination;
    }

    public function setPagination(PaginationObject $pagination): self
    {
        $this->initialized['pagination'] = true;
        $this->pagination = $pagination;

        return $this;
    }

    /**
     * The list of country states for the given country.
     *
     * @return list<GetCountryCountryStates200ResponseCountryStates>
     */
    public function getCountryStates(): array
    {
        return $this->countryStates;
    }

    /**
     * The list of country states for the given country.
     *
     * @param list<GetCountryCountryStates200ResponseCountryStates> $countryStates
     */
    public function setCountryStates(array $countryStates): self
    {
        $this->initialized['countryStates'] = true;
        $this->countryStates = $countryStates;

        return $this;
    }
}
