<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class DiskBackupPolicyArguments extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var int
     */
    protected $retention;
    /**
     * @var ScheduleArguments
     */
    protected $schedule;

    public function getRetention(): int
    {
        return $this->retention;
    }

    public function setRetention(int $retention): self
    {
        $this->initialized['retention'] = true;
        $this->retention = $retention;

        return $this;
    }

    public function getSchedule(): ScheduleArguments
    {
        return $this->schedule;
    }

    public function setSchedule(ScheduleArguments $schedule): self
    {
        $this->initialized['schedule'] = true;
        $this->schedule = $schedule;

        return $this;
    }
}
