<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class DnsRecordsDnsRecordPatchBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var DNSRecordLookup
     */
    protected $dnsRecord;
    /**
     * @var DNSRecordArguments
     */
    protected $properties;

    public function getDnsRecord(): DNSRecordLookup
    {
        return $this->dnsRecord;
    }

    public function setDnsRecord(DNSRecordLookup $dnsRecord): self
    {
        $this->initialized['dnsRecord'] = true;
        $this->dnsRecord = $dnsRecord;

        return $this;
    }

    public function getProperties(): DNSRecordArguments
    {
        return $this->properties;
    }

    public function setProperties(DNSRecordArguments $properties): self
    {
        $this->initialized['properties'] = true;
        $this->properties = $properties;

        return $this;
    }
}
