<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class LoadBalancerResource extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    protected $resources;

    public function getResources()
    {
        return $this->resources;
    }

    public function setResources($resources): self
    {
        $this->initialized['resources'] = true;
        $this->resources = $resources;

        return $this;
    }
}
