<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class ObjectStorageAccessKeysAccessKeyPatchResponse200 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The new properties for the object storage access key.
     *
     * @var ObjectStorageAccessKeysAccessKeyPatchResponse200ObjectStorageAccessKey
     */
    protected $objectStorageAccessKey;

    /**
     * The new properties for the object storage access key.
     */
    public function getObjectStorageAccessKey(): ObjectStorageAccessKeysAccessKeyPatchResponse200ObjectStorageAccessKey
    {
        return $this->objectStorageAccessKey;
    }

    /**
     * The new properties for the object storage access key.
     */
    public function setObjectStorageAccessKey(ObjectStorageAccessKeysAccessKeyPatchResponse200ObjectStorageAccessKey $objectStorageAccessKey): self
    {
        $this->initialized['objectStorageAccessKey'] = true;
        $this->objectStorageAccessKey = $objectStorageAccessKey;

        return $this;
    }
}
