<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class OrganizationsOrganizationObjectStorageObjectStorageClusterGetResponse200 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var ObjectStorageAccount
     */
    protected $objectStorageAccount;

    public function getObjectStorageAccount(): ObjectStorageAccount
    {
        return $this->objectStorageAccount;
    }

    public function setObjectStorageAccount(ObjectStorageAccount $objectStorageAccount): self
    {
        $this->initialized['objectStorageAccount'] = true;
        $this->objectStorageAccount = $objectStorageAccount;

        return $this;
    }
}
