<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class OrganizationsOrganizationCertificatesGetResponse200 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var PaginationObject
     */
    protected $pagination;
    /**
     * @var list<GetOrganizationCertificates200ResponseCertificates>
     */
    protected $certificates;

    public function getPagination(): PaginationObject
    {
        return $this->pagination;
    }

    public function setPagination(PaginationObject $pagination): self
    {
        $this->initialized['pagination'] = true;
        $this->pagination = $pagination;

        return $this;
    }

    /**
     * @return list<GetOrganizationCertificates200ResponseCertificates>
     */
    public function getCertificates(): array
    {
        return $this->certificates;
    }

    /**
     * @param list<GetOrganizationCertificates200ResponseCertificates> $certificates
     */
    public function setCertificates(array $certificates): self
    {
        $this->initialized['certificates'] = true;
        $this->certificates = $certificates;

        return $this;
    }
}
