<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class OrganizationsOrganizationVirtualNetworksPostResponse200 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The new virtual network details.
     *
     * @var OrganizationsOrganizationVirtualNetworksPostResponse200VirtualNetwork
     */
    protected $virtualNetwork;

    /**
     * The new virtual network details.
     */
    public function getVirtualNetwork(): OrganizationsOrganizationVirtualNetworksPostResponse200VirtualNetwork
    {
        return $this->virtualNetwork;
    }

    /**
     * The new virtual network details.
     */
    public function setVirtualNetwork(OrganizationsOrganizationVirtualNetworksPostResponse200VirtualNetwork $virtualNetwork): self
    {
        $this->initialized['virtualNetwork'] = true;
        $this->virtualNetwork = $virtualNetwork;

        return $this;
    }
}
