<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class OrganizationsOrganizationDnsZonesPostBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * All 'organization[]' params are mutually exclusive, only one can be provided.
     *
     * @var OrganizationLookup
     */
    protected $organization;
    /**
     * All 'properties[]' params are mutually exclusive, only one can be provided.
     *
     * @var DNSZoneArguments
     */
    protected $properties;
    /**
     * Creates a zone without requiring any verification to be performed. Internal use only (this
     * requires the 'dns_zones:create:verified' capability).
     *
     * @var bool
     */
    protected $verified;

    /**
     * All 'organization[]' params are mutually exclusive, only one can be provided.
     */
    public function getOrganization(): OrganizationLookup
    {
        return $this->organization;
    }

    /**
     * All 'organization[]' params are mutually exclusive, only one can be provided.
     */
    public function setOrganization(OrganizationLookup $organization): self
    {
        $this->initialized['organization'] = true;
        $this->organization = $organization;

        return $this;
    }

    /**
     * All 'properties[]' params are mutually exclusive, only one can be provided.
     */
    public function getProperties(): DNSZoneArguments
    {
        return $this->properties;
    }

    /**
     * All 'properties[]' params are mutually exclusive, only one can be provided.
     */
    public function setProperties(DNSZoneArguments $properties): self
    {
        $this->initialized['properties'] = true;
        $this->properties = $properties;

        return $this;
    }

    /**
     * Creates a zone without requiring any verification to be performed. Internal use only (this
     * requires the 'dns_zones:create:verified' capability).
     */
    public function getVerified(): bool
    {
        return $this->verified;
    }

    /**
     * Creates a zone without requiring any verification to be performed. Internal use only (this
     * requires the 'dns_zones:create:verified' capability).
     */
    public function setVerified(bool $verified): self
    {
        $this->initialized['verified'] = true;
        $this->verified = $verified;

        return $this;
    }
}
