<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class PolicyFeatures extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var PolicyFeature
     */
    protected $diskBusConfiguration;
    /**
     * @var PolicyFeature
     */
    protected $zoneSelection;
    /**
     * @var PolicyFeature
     */
    protected $restrictedTrafficTypes;
    /**
     * @var PolicyFeature
     */
    protected $suspension;
    /**
     * @var PolicyFeature
     */
    protected $flexibleVirtualMachineResources;

    public function getDiskBusConfiguration(): PolicyFeature
    {
        return $this->diskBusConfiguration;
    }

    public function setDiskBusConfiguration(PolicyFeature $diskBusConfiguration): self
    {
        $this->initialized['diskBusConfiguration'] = true;
        $this->diskBusConfiguration = $diskBusConfiguration;

        return $this;
    }

    public function getZoneSelection(): PolicyFeature
    {
        return $this->zoneSelection;
    }

    public function setZoneSelection(PolicyFeature $zoneSelection): self
    {
        $this->initialized['zoneSelection'] = true;
        $this->zoneSelection = $zoneSelection;

        return $this;
    }

    public function getRestrictedTrafficTypes(): PolicyFeature
    {
        return $this->restrictedTrafficTypes;
    }

    public function setRestrictedTrafficTypes(PolicyFeature $restrictedTrafficTypes): self
    {
        $this->initialized['restrictedTrafficTypes'] = true;
        $this->restrictedTrafficTypes = $restrictedTrafficTypes;

        return $this;
    }

    public function getSuspension(): PolicyFeature
    {
        return $this->suspension;
    }

    public function setSuspension(PolicyFeature $suspension): self
    {
        $this->initialized['suspension'] = true;
        $this->suspension = $suspension;

        return $this;
    }

    public function getFlexibleVirtualMachineResources(): PolicyFeature
    {
        return $this->flexibleVirtualMachineResources;
    }

    public function setFlexibleVirtualMachineResources(PolicyFeature $flexibleVirtualMachineResources): self
    {
        $this->initialized['flexibleVirtualMachineResources'] = true;
        $this->flexibleVirtualMachineResources = $flexibleVirtualMachineResources;

        return $this;
    }
}
