<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class SecurityGroupsRulesSecurityGroupRuleDeleteBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var SecurityGroupRuleLookup
     */
    protected $securityGroupRule;

    public function getSecurityGroupRule(): SecurityGroupRuleLookup
    {
        return $this->securityGroupRule;
    }

    public function setSecurityGroupRule(SecurityGroupRuleLookup $securityGroupRule): self
    {
        $this->initialized['securityGroupRule'] = true;
        $this->securityGroupRule = $securityGroupRule;

        return $this;
    }
}
