<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Model;

class VirtualMachineGroupArguments extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $name;
    /**
     * @var bool
     */
    protected $segregate;
    /**
     * @var bool
     */
    protected $autoSegregate;

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    public function getSegregate(): bool
    {
        return $this->segregate;
    }

    public function setSegregate(bool $segregate): self
    {
        $this->initialized['segregate'] = true;
        $this->segregate = $segregate;

        return $this;
    }

    public function getAutoSegregate(): bool
    {
        return $this->autoSegregate;
    }

    public function setAutoSegregate(bool $autoSegregate): self
    {
        $this->initialized['autoSegregate'] = true;
        $this->autoSegregate = $autoSegregate;

        return $this;
    }
}
