<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use Krystal\Katapult\KatapultAPI\Runtime\Normalizer\CheckArray;
use Krystal\Katapult\KatapultAPI\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class DNSRecordContentAttributesNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributes';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributes';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Krystal\Katapult\KatapultAPI\Model\DNSRecordContentAttributes();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('A', $data) && $data['A'] !== null) {
                $object->setA($this->denormalizer->denormalize($data['A'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesA', 'json', $context));
                unset($data['A']);
            } elseif (\array_key_exists('A', $data) && $data['A'] === null) {
                $object->setA(null);
            }
            if (\array_key_exists('AAAA', $data) && $data['AAAA'] !== null) {
                $object->setAAAA($this->denormalizer->denormalize($data['AAAA'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesAAAA', 'json', $context));
                unset($data['AAAA']);
            } elseif (\array_key_exists('AAAA', $data) && $data['AAAA'] === null) {
                $object->setAAAA(null);
            }
            if (\array_key_exists('ALIAS', $data) && $data['ALIAS'] !== null) {
                $object->setALIAS($this->denormalizer->denormalize($data['ALIAS'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesALIAS', 'json', $context));
                unset($data['ALIAS']);
            } elseif (\array_key_exists('ALIAS', $data) && $data['ALIAS'] === null) {
                $object->setALIAS(null);
            }
            if (\array_key_exists('CAA', $data) && $data['CAA'] !== null) {
                $object->setCAA($this->denormalizer->denormalize($data['CAA'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesCAA', 'json', $context));
                unset($data['CAA']);
            } elseif (\array_key_exists('CAA', $data) && $data['CAA'] === null) {
                $object->setCAA(null);
            }
            if (\array_key_exists('CNAME', $data) && $data['CNAME'] !== null) {
                $object->setCNAME($this->denormalizer->denormalize($data['CNAME'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesCNAME', 'json', $context));
                unset($data['CNAME']);
            } elseif (\array_key_exists('CNAME', $data) && $data['CNAME'] === null) {
                $object->setCNAME(null);
            }
            if (\array_key_exists('IPS', $data) && $data['IPS'] !== null) {
                $object->setIPS($this->denormalizer->denormalize($data['IPS'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesIPS', 'json', $context));
                unset($data['IPS']);
            } elseif (\array_key_exists('IPS', $data) && $data['IPS'] === null) {
                $object->setIPS(null);
            }
            if (\array_key_exists('MX', $data) && $data['MX'] !== null) {
                $object->setMX($this->denormalizer->denormalize($data['MX'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesMX', 'json', $context));
                unset($data['MX']);
            } elseif (\array_key_exists('MX', $data) && $data['MX'] === null) {
                $object->setMX(null);
            }
            if (\array_key_exists('NS', $data) && $data['NS'] !== null) {
                $object->setNS($this->denormalizer->denormalize($data['NS'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesNS', 'json', $context));
                unset($data['NS']);
            } elseif (\array_key_exists('NS', $data) && $data['NS'] === null) {
                $object->setNS(null);
            }
            if (\array_key_exists('PTR', $data) && $data['PTR'] !== null) {
                $object->setPTR($this->denormalizer->denormalize($data['PTR'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesPTR', 'json', $context));
                unset($data['PTR']);
            } elseif (\array_key_exists('PTR', $data) && $data['PTR'] === null) {
                $object->setPTR(null);
            }
            if (\array_key_exists('SOA', $data) && $data['SOA'] !== null) {
                $values = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
                foreach ($data['SOA'] as $key => $value) {
                    $values[$key] = $value;
                }
                $object->setSOA($values);
                unset($data['SOA']);
            } elseif (\array_key_exists('SOA', $data) && $data['SOA'] === null) {
                $object->setSOA(null);
            }
            if (\array_key_exists('SRV', $data) && $data['SRV'] !== null) {
                $object->setSRV($this->denormalizer->denormalize($data['SRV'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesSRV', 'json', $context));
                unset($data['SRV']);
            } elseif (\array_key_exists('SRV', $data) && $data['SRV'] === null) {
                $object->setSRV(null);
            }
            if (\array_key_exists('SSHFP', $data) && $data['SSHFP'] !== null) {
                $object->setSSHFP($this->denormalizer->denormalize($data['SSHFP'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesSSHFP', 'json', $context));
                unset($data['SSHFP']);
            } elseif (\array_key_exists('SSHFP', $data) && $data['SSHFP'] === null) {
                $object->setSSHFP(null);
            }
            if (\array_key_exists('TXT', $data) && $data['TXT'] !== null) {
                $object->setTXT($this->denormalizer->denormalize($data['TXT'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesTXT', 'json', $context));
                unset($data['TXT']);
            } elseif (\array_key_exists('TXT', $data) && $data['TXT'] === null) {
                $object->setTXT(null);
            }
            if (\array_key_exists('VirtualMachine', $data) && $data['VirtualMachine'] !== null) {
                $object->setVirtualMachine($this->denormalizer->denormalize($data['VirtualMachine'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesVirtualMachine', 'json', $context));
                unset($data['VirtualMachine']);
            } elseif (\array_key_exists('VirtualMachine', $data) && $data['VirtualMachine'] === null) {
                $object->setVirtualMachine(null);
            }
            foreach ($data as $key_1 => $value_1) {
                if (preg_match('/.*/', (string) $key_1)) {
                    $object[$key_1] = $value_1;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('a') && null !== $object->getA()) {
                $data['A'] = $this->normalizer->normalize($object->getA(), 'json', $context);
            }
            if ($object->isInitialized('aAAA') && null !== $object->getAAAA()) {
                $data['AAAA'] = $this->normalizer->normalize($object->getAAAA(), 'json', $context);
            }
            if ($object->isInitialized('aLIAS') && null !== $object->getALIAS()) {
                $data['ALIAS'] = $this->normalizer->normalize($object->getALIAS(), 'json', $context);
            }
            if ($object->isInitialized('cAA') && null !== $object->getCAA()) {
                $data['CAA'] = $this->normalizer->normalize($object->getCAA(), 'json', $context);
            }
            if ($object->isInitialized('cNAME') && null !== $object->getCNAME()) {
                $data['CNAME'] = $this->normalizer->normalize($object->getCNAME(), 'json', $context);
            }
            if ($object->isInitialized('iPS') && null !== $object->getIPS()) {
                $data['IPS'] = $this->normalizer->normalize($object->getIPS(), 'json', $context);
            }
            if ($object->isInitialized('mX') && null !== $object->getMX()) {
                $data['MX'] = $this->normalizer->normalize($object->getMX(), 'json', $context);
            }
            if ($object->isInitialized('nS') && null !== $object->getNS()) {
                $data['NS'] = $this->normalizer->normalize($object->getNS(), 'json', $context);
            }
            if ($object->isInitialized('pTR') && null !== $object->getPTR()) {
                $data['PTR'] = $this->normalizer->normalize($object->getPTR(), 'json', $context);
            }
            if ($object->isInitialized('sOA') && null !== $object->getSOA()) {
                $values = [];
                foreach ($object->getSOA() as $key => $value) {
                    $values[$key] = $value;
                }
                $data['SOA'] = $values;
            }
            if ($object->isInitialized('sRV') && null !== $object->getSRV()) {
                $data['SRV'] = $this->normalizer->normalize($object->getSRV(), 'json', $context);
            }
            if ($object->isInitialized('sSHFP') && null !== $object->getSSHFP()) {
                $data['SSHFP'] = $this->normalizer->normalize($object->getSSHFP(), 'json', $context);
            }
            if ($object->isInitialized('tXT') && null !== $object->getTXT()) {
                $data['TXT'] = $this->normalizer->normalize($object->getTXT(), 'json', $context);
            }
            if ($object->isInitialized('virtualMachine') && null !== $object->getVirtualMachine()) {
                $data['VirtualMachine'] = $this->normalizer->normalize($object->getVirtualMachine(), 'json', $context);
            }
            foreach ($object as $key_1 => $value_1) {
                if (preg_match('/.*/', (string) $key_1)) {
                    $data[$key_1] = $value_1;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributes' => false];
        }
    }
} else {
    class DNSRecordContentAttributesNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributes';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributes';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Krystal\Katapult\KatapultAPI\Model\DNSRecordContentAttributes();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('A', $data) && $data['A'] !== null) {
                $object->setA($this->denormalizer->denormalize($data['A'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesA', 'json', $context));
                unset($data['A']);
            } elseif (\array_key_exists('A', $data) && $data['A'] === null) {
                $object->setA(null);
            }
            if (\array_key_exists('AAAA', $data) && $data['AAAA'] !== null) {
                $object->setAAAA($this->denormalizer->denormalize($data['AAAA'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesAAAA', 'json', $context));
                unset($data['AAAA']);
            } elseif (\array_key_exists('AAAA', $data) && $data['AAAA'] === null) {
                $object->setAAAA(null);
            }
            if (\array_key_exists('ALIAS', $data) && $data['ALIAS'] !== null) {
                $object->setALIAS($this->denormalizer->denormalize($data['ALIAS'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesALIAS', 'json', $context));
                unset($data['ALIAS']);
            } elseif (\array_key_exists('ALIAS', $data) && $data['ALIAS'] === null) {
                $object->setALIAS(null);
            }
            if (\array_key_exists('CAA', $data) && $data['CAA'] !== null) {
                $object->setCAA($this->denormalizer->denormalize($data['CAA'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesCAA', 'json', $context));
                unset($data['CAA']);
            } elseif (\array_key_exists('CAA', $data) && $data['CAA'] === null) {
                $object->setCAA(null);
            }
            if (\array_key_exists('CNAME', $data) && $data['CNAME'] !== null) {
                $object->setCNAME($this->denormalizer->denormalize($data['CNAME'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesCNAME', 'json', $context));
                unset($data['CNAME']);
            } elseif (\array_key_exists('CNAME', $data) && $data['CNAME'] === null) {
                $object->setCNAME(null);
            }
            if (\array_key_exists('IPS', $data) && $data['IPS'] !== null) {
                $object->setIPS($this->denormalizer->denormalize($data['IPS'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesIPS', 'json', $context));
                unset($data['IPS']);
            } elseif (\array_key_exists('IPS', $data) && $data['IPS'] === null) {
                $object->setIPS(null);
            }
            if (\array_key_exists('MX', $data) && $data['MX'] !== null) {
                $object->setMX($this->denormalizer->denormalize($data['MX'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesMX', 'json', $context));
                unset($data['MX']);
            } elseif (\array_key_exists('MX', $data) && $data['MX'] === null) {
                $object->setMX(null);
            }
            if (\array_key_exists('NS', $data) && $data['NS'] !== null) {
                $object->setNS($this->denormalizer->denormalize($data['NS'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesNS', 'json', $context));
                unset($data['NS']);
            } elseif (\array_key_exists('NS', $data) && $data['NS'] === null) {
                $object->setNS(null);
            }
            if (\array_key_exists('PTR', $data) && $data['PTR'] !== null) {
                $object->setPTR($this->denormalizer->denormalize($data['PTR'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesPTR', 'json', $context));
                unset($data['PTR']);
            } elseif (\array_key_exists('PTR', $data) && $data['PTR'] === null) {
                $object->setPTR(null);
            }
            if (\array_key_exists('SOA', $data) && $data['SOA'] !== null) {
                $values = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
                foreach ($data['SOA'] as $key => $value) {
                    $values[$key] = $value;
                }
                $object->setSOA($values);
                unset($data['SOA']);
            } elseif (\array_key_exists('SOA', $data) && $data['SOA'] === null) {
                $object->setSOA(null);
            }
            if (\array_key_exists('SRV', $data) && $data['SRV'] !== null) {
                $object->setSRV($this->denormalizer->denormalize($data['SRV'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesSRV', 'json', $context));
                unset($data['SRV']);
            } elseif (\array_key_exists('SRV', $data) && $data['SRV'] === null) {
                $object->setSRV(null);
            }
            if (\array_key_exists('SSHFP', $data) && $data['SSHFP'] !== null) {
                $object->setSSHFP($this->denormalizer->denormalize($data['SSHFP'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesSSHFP', 'json', $context));
                unset($data['SSHFP']);
            } elseif (\array_key_exists('SSHFP', $data) && $data['SSHFP'] === null) {
                $object->setSSHFP(null);
            }
            if (\array_key_exists('TXT', $data) && $data['TXT'] !== null) {
                $object->setTXT($this->denormalizer->denormalize($data['TXT'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesTXT', 'json', $context));
                unset($data['TXT']);
            } elseif (\array_key_exists('TXT', $data) && $data['TXT'] === null) {
                $object->setTXT(null);
            }
            if (\array_key_exists('VirtualMachine', $data) && $data['VirtualMachine'] !== null) {
                $object->setVirtualMachine($this->denormalizer->denormalize($data['VirtualMachine'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributesVirtualMachine', 'json', $context));
                unset($data['VirtualMachine']);
            } elseif (\array_key_exists('VirtualMachine', $data) && $data['VirtualMachine'] === null) {
                $object->setVirtualMachine(null);
            }
            foreach ($data as $key_1 => $value_1) {
                if (preg_match('/.*/', (string) $key_1)) {
                    $object[$key_1] = $value_1;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('a') && null !== $object->getA()) {
                $data['A'] = $this->normalizer->normalize($object->getA(), 'json', $context);
            }
            if ($object->isInitialized('aAAA') && null !== $object->getAAAA()) {
                $data['AAAA'] = $this->normalizer->normalize($object->getAAAA(), 'json', $context);
            }
            if ($object->isInitialized('aLIAS') && null !== $object->getALIAS()) {
                $data['ALIAS'] = $this->normalizer->normalize($object->getALIAS(), 'json', $context);
            }
            if ($object->isInitialized('cAA') && null !== $object->getCAA()) {
                $data['CAA'] = $this->normalizer->normalize($object->getCAA(), 'json', $context);
            }
            if ($object->isInitialized('cNAME') && null !== $object->getCNAME()) {
                $data['CNAME'] = $this->normalizer->normalize($object->getCNAME(), 'json', $context);
            }
            if ($object->isInitialized('iPS') && null !== $object->getIPS()) {
                $data['IPS'] = $this->normalizer->normalize($object->getIPS(), 'json', $context);
            }
            if ($object->isInitialized('mX') && null !== $object->getMX()) {
                $data['MX'] = $this->normalizer->normalize($object->getMX(), 'json', $context);
            }
            if ($object->isInitialized('nS') && null !== $object->getNS()) {
                $data['NS'] = $this->normalizer->normalize($object->getNS(), 'json', $context);
            }
            if ($object->isInitialized('pTR') && null !== $object->getPTR()) {
                $data['PTR'] = $this->normalizer->normalize($object->getPTR(), 'json', $context);
            }
            if ($object->isInitialized('sOA') && null !== $object->getSOA()) {
                $values = [];
                foreach ($object->getSOA() as $key => $value) {
                    $values[$key] = $value;
                }
                $data['SOA'] = $values;
            }
            if ($object->isInitialized('sRV') && null !== $object->getSRV()) {
                $data['SRV'] = $this->normalizer->normalize($object->getSRV(), 'json', $context);
            }
            if ($object->isInitialized('sSHFP') && null !== $object->getSSHFP()) {
                $data['SSHFP'] = $this->normalizer->normalize($object->getSSHFP(), 'json', $context);
            }
            if ($object->isInitialized('tXT') && null !== $object->getTXT()) {
                $data['TXT'] = $this->normalizer->normalize($object->getTXT(), 'json', $context);
            }
            if ($object->isInitialized('virtualMachine') && null !== $object->getVirtualMachine()) {
                $data['VirtualMachine'] = $this->normalizer->normalize($object->getVirtualMachine(), 'json', $context);
            }
            foreach ($object as $key_1 => $value_1) {
                if (preg_match('/.*/', (string) $key_1)) {
                    $data[$key_1] = $value_1;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Krystal\\Katapult\\KatapultAPI\\Model\\DNSRecordContentAttributes' => false];
        }
    }
}
