<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use Krystal\Katapult\KatapultAPI\Runtime\Normalizer\CheckArray;
use Krystal\Katapult\KatapultAPI\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class PostDiskAssign200ResponseDiskInstallationNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Krystal\\Katapult\\KatapultAPI\\Model\\PostDiskAssign200ResponseDiskInstallation';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Krystal\\Katapult\\KatapultAPI\\Model\\PostDiskAssign200ResponseDiskInstallation';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Krystal\Katapult\KatapultAPI\Model\PostDiskAssign200ResponseDiskInstallation();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('id', $data)) {
                $object->setId($data['id']);
                unset($data['id']);
            }
            if (\array_key_exists('disk_template_version', $data)) {
                $object->setDiskTemplateVersion($this->denormalizer->denormalize($data['disk_template_version'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DiskTemplateVersion', 'json', $context));
                unset($data['disk_template_version']);
            }
            if (\array_key_exists('attributes', $data)) {
                $values = [];
                foreach ($data['attributes'] as $value) {
                    $values[] = $this->denormalizer->denormalize($value, 'Krystal\\Katapult\\KatapultAPI\\Model\\DiskInstallationAttribute', 'json', $context);
                }
                $object->setAttributes($values);
                unset($data['attributes']);
            }
            foreach ($data as $key => $value_1) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value_1;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('id') && null !== $object->getId()) {
                $data['id'] = $object->getId();
            }
            if ($object->isInitialized('diskTemplateVersion') && null !== $object->getDiskTemplateVersion()) {
                $data['disk_template_version'] = $this->normalizer->normalize($object->getDiskTemplateVersion(), 'json', $context);
            }
            if ($object->isInitialized('attributes') && null !== $object->getAttributes()) {
                $values = [];
                foreach ($object->getAttributes() as $value) {
                    $values[] = $this->normalizer->normalize($value, 'json', $context);
                }
                $data['attributes'] = $values;
            }
            foreach ($object as $key => $value_1) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value_1;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Krystal\\Katapult\\KatapultAPI\\Model\\PostDiskAssign200ResponseDiskInstallation' => false];
        }
    }
} else {
    class PostDiskAssign200ResponseDiskInstallationNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Krystal\\Katapult\\KatapultAPI\\Model\\PostDiskAssign200ResponseDiskInstallation';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Krystal\\Katapult\\KatapultAPI\\Model\\PostDiskAssign200ResponseDiskInstallation';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Krystal\Katapult\KatapultAPI\Model\PostDiskAssign200ResponseDiskInstallation();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('id', $data)) {
                $object->setId($data['id']);
                unset($data['id']);
            }
            if (\array_key_exists('disk_template_version', $data)) {
                $object->setDiskTemplateVersion($this->denormalizer->denormalize($data['disk_template_version'], 'Krystal\\Katapult\\KatapultAPI\\Model\\DiskTemplateVersion', 'json', $context));
                unset($data['disk_template_version']);
            }
            if (\array_key_exists('attributes', $data)) {
                $values = [];
                foreach ($data['attributes'] as $value) {
                    $values[] = $this->denormalizer->denormalize($value, 'Krystal\\Katapult\\KatapultAPI\\Model\\DiskInstallationAttribute', 'json', $context);
                }
                $object->setAttributes($values);
                unset($data['attributes']);
            }
            foreach ($data as $key => $value_1) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value_1;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('id') && null !== $object->getId()) {
                $data['id'] = $object->getId();
            }
            if ($object->isInitialized('diskTemplateVersion') && null !== $object->getDiskTemplateVersion()) {
                $data['disk_template_version'] = $this->normalizer->normalize($object->getDiskTemplateVersion(), 'json', $context);
            }
            if ($object->isInitialized('attributes') && null !== $object->getAttributes()) {
                $values = [];
                foreach ($object->getAttributes() as $value) {
                    $values[] = $this->normalizer->normalize($value, 'json', $context);
                }
                $data['attributes'] = $values;
            }
            foreach ($object as $key => $value_1) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value_1;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Krystal\\Katapult\\KatapultAPI\\Model\\PostDiskAssign200ResponseDiskInstallation' => false];
        }
    }
}
