<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Model;

class CurrenciesGetResponse200 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var CurrenciesGetResponse200Pagination
     */
    protected $pagination;
    /**
     * The list of currencies.
     *
     * @var GetCurrencies200ResponseCurrencies[]
     */
    protected $currencies;

    public function getPagination(): CurrenciesGetResponse200Pagination
    {
        return $this->pagination;
    }

    public function setPagination(CurrenciesGetResponse200Pagination $pagination): self
    {
        $this->initialized['pagination'] = true;
        $this->pagination = $pagination;

        return $this;
    }

    /**
     * The list of currencies.
     *
     * @return GetCurrencies200ResponseCurrencies[]
     */
    public function getCurrencies(): array
    {
        return $this->currencies;
    }

    /**
     * The list of currencies.
     *
     * @param GetCurrencies200ResponseCurrencies[] $currencies
     */
    public function setCurrencies(array $currencies): self
    {
        $this->initialized['currencies'] = true;
        $this->currencies = $currencies;

        return $this;
    }
}
