<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Model;

class GetDiskTemplateVersion200ResponseDiskTemplateVersion extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $id;
    /**
     * @var int
     */
    protected $number;
    /**
     * @var bool
     */
    protected $stable;
    /**
     * @var int
     */
    protected $sizeInGb;
    /**
     * @var GetDiskTemplateVersion200ResponseDiskTemplateVersionDiskTemplate
     */
    protected $diskTemplate;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getNumber(): int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->initialized['number'] = true;
        $this->number = $number;

        return $this;
    }

    public function getStable(): bool
    {
        return $this->stable;
    }

    public function setStable(bool $stable): self
    {
        $this->initialized['stable'] = true;
        $this->stable = $stable;

        return $this;
    }

    public function getSizeInGb(): int
    {
        return $this->sizeInGb;
    }

    public function setSizeInGb(int $sizeInGb): self
    {
        $this->initialized['sizeInGb'] = true;
        $this->sizeInGb = $sizeInGb;

        return $this;
    }

    public function getDiskTemplate(): GetDiskTemplateVersion200ResponseDiskTemplateVersionDiskTemplate
    {
        return $this->diskTemplate;
    }

    public function setDiskTemplate(GetDiskTemplateVersion200ResponseDiskTemplateVersionDiskTemplate $diskTemplate): self
    {
        $this->initialized['diskTemplate'] = true;
        $this->diskTemplate = $diskTemplate;

        return $this;
    }
}
