<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Model;

class OrganizationsOrganizationSshKeysPostBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * All 'organization[]' params are mutually exclusive, only one can be provided.
     *
     * @var OrganizationLookup
     */
    protected $organization;
    /**
     * All 'ssh_key[]' params are mutually exclusive, only one can be provided.
     *
     * @var AuthSSHKeyProperties
     */
    protected $sshKey;

    /**
     * All 'organization[]' params are mutually exclusive, only one can be provided.
     */
    public function getOrganization(): OrganizationLookup
    {
        return $this->organization;
    }

    /**
     * All 'organization[]' params are mutually exclusive, only one can be provided.
     */
    public function setOrganization(OrganizationLookup $organization): self
    {
        $this->initialized['organization'] = true;
        $this->organization = $organization;

        return $this;
    }

    /**
     * All 'ssh_key[]' params are mutually exclusive, only one can be provided.
     */
    public function getSshKey(): AuthSSHKeyProperties
    {
        return $this->sshKey;
    }

    /**
     * All 'ssh_key[]' params are mutually exclusive, only one can be provided.
     */
    public function setSshKey(AuthSSHKeyProperties $sshKey): self
    {
        $this->initialized['sshKey'] = true;
        $this->sshKey = $sshKey;

        return $this;
    }
}
