<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Model;

class SecurityGroupsRulesSecurityGroupRuleGetResponse200 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The resolved security group rule.
     *
     * @var SecurityGroupsRulesSecurityGroupRuleGetResponse200SecurityGroupRule
     */
    protected $securityGroupRule;

    /**
     * The resolved security group rule.
     */
    public function getSecurityGroupRule(): SecurityGroupsRulesSecurityGroupRuleGetResponse200SecurityGroupRule
    {
        return $this->securityGroupRule;
    }

    /**
     * The resolved security group rule.
     */
    public function setSecurityGroupRule(SecurityGroupsRulesSecurityGroupRuleGetResponse200SecurityGroupRule $securityGroupRule): self
    {
        $this->initialized['securityGroupRule'] = true;
        $this->securityGroupRule = $securityGroupRule;

        return $this;
    }
}
