<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Model;

class SSHFP extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $algorithm;
    /**
     * @var string
     */
    protected $fingerprintType;
    /**
     * @var string
     */
    protected $fingerprint;

    public function getAlgorithm(): string
    {
        return $this->algorithm;
    }

    public function setAlgorithm(string $algorithm): self
    {
        $this->initialized['algorithm'] = true;
        $this->algorithm = $algorithm;

        return $this;
    }

    public function getFingerprintType(): string
    {
        return $this->fingerprintType;
    }

    public function setFingerprintType(string $fingerprintType): self
    {
        $this->initialized['fingerprintType'] = true;
        $this->fingerprintType = $fingerprintType;

        return $this;
    }

    public function getFingerprint(): string
    {
        return $this->fingerprint;
    }

    public function setFingerprint(string $fingerprint): self
    {
        $this->initialized['fingerprint'] = true;
        $this->fingerprint = $fingerprint;

        return $this;
    }
}
