<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Model;

class UnauthorizedNetworkForAPIToken extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The IP address the request was received from.
     *
     * @var string
     */
    protected $ipAddress;

    /**
     * The IP address the request was received from.
     */
    public function getIpAddress(): string
    {
        return $this->ipAddress;
    }

    /**
     * The IP address the request was received from.
     */
    public function setIpAddress(string $ipAddress): self
    {
        $this->initialized['ipAddress'] = true;
        $this->ipAddress = $ipAddress;

        return $this;
    }
}
