<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Model;

class VirtualMachinesVirtualMachineStartPostResponse200 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var VirtualMachinesVirtualMachineStartPostResponse200Task
     */
    protected $task;

    public function getTask(): VirtualMachinesVirtualMachineStartPostResponse200Task
    {
        return $this->task;
    }

    public function setTask(VirtualMachinesVirtualMachineStartPostResponse200Task $task): self
    {
        $this->initialized['task'] = true;
        $this->task = $task;

        return $this;
    }
}
