<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Endpoint;

class PatchObjectStorageObjectStorageClusterBucket extends \KatapultAPI\Core\Runtime\Client\BaseEndpoint implements \KatapultAPI\Core\Runtime\Client\Endpoint
{
    use \KatapultAPI\Core\Runtime\Client\EndpointTrait;

    /**
     * Configure an object storage bucket with new properties
     * ## Scopes
     * - `object_storage`.
     *
     * ### OAuth2 Scopes
     * When using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.
     */
    public function __construct(?\KatapultAPI\Core\Model\ObjectStorageObjectStorageClusterBucketsBucketPatchBody $requestBody = null)
    {
        $this->body = $requestBody;
    }

    public function getMethod(): string
    {
        return 'PATCH';
    }

    public function getUri(): string
    {
        return '/object_storage/object_storage_cluster/buckets/bucket';
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        if ($this->body instanceof \KatapultAPI\Core\Model\ObjectStorageObjectStorageClusterBucketsBucketPatchBody) {
            return [['Content-Type' => ['application/json']], $serializer->serialize($this->body, 'json')];
        }

        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    /**
     * @return \KatapultAPI\Core\Model\ObjectStorageObjectStorageClusterBucketsBucketPatchResponse200|null
     *
     * @throws \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketBadRequestException
     * @throws \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketForbiddenException
     * @throws \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketNotFoundException
     * @throws \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketNotAcceptableException
     * @throws \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketUnprocessableEntityException
     * @throws \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketTooManyRequestsException
     * @throws \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketInternalServerErrorException
     * @throws \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketServiceUnavailableException
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (is_null($contentType) === false && (200 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            return $serializer->deserialize($body, 'KatapultAPI\Core\Model\ObjectStorageObjectStorageClusterBucketsBucketPatchResponse200', 'json');
        }
        if (is_null($contentType) === false && (400 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketBadRequestException($serializer->deserialize($body, 'KatapultAPI\Core\Model\ResponseAPIAuthenticator400Response', 'json'), $response);
        }
        if (is_null($contentType) === false && (403 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketForbiddenException($response);
        }
        if (is_null($contentType) === false && (404 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketNotFoundException($response);
        }
        if (is_null($contentType) === false && (406 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketNotAcceptableException($serializer->deserialize($body, 'KatapultAPI\Core\Model\ResponseObjectInTrashResponse', 'json'), $response);
        }
        if (is_null($contentType) === false && (422 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketUnprocessableEntityException($serializer->deserialize($body, 'KatapultAPI\Core\Model\ResponseValidationErrorResponse', 'json'), $response);
        }
        if (is_null($contentType) === false && (429 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketTooManyRequestsException($serializer->deserialize($body, 'KatapultAPI\Core\Model\ResponseAPIAuthenticator429Response', 'json'), $response);
        }
        if (is_null($contentType) === false && (500 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketInternalServerErrorException($serializer->deserialize($body, 'KatapultAPI\Core\Model\ResponseMultipleObjectStorageBucketsFoundResponse', 'json'), $response);
        }
        if (is_null($contentType) === false && (503 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \KatapultAPI\Core\Exception\PatchObjectStorageObjectStorageClusterBucketServiceUnavailableException($serializer->deserialize($body, 'KatapultAPI\Core\Model\ResponseAPIAuthenticator503Response', 'json'), $response);
        }
    }

    public function getAuthenticationScopes(): array
    {
        return ['OAuth2', 'Authenticator'];
    }
}
