<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Core\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use KatapultAPI\Core\Runtime\Normalizer\CheckArray;
use KatapultAPI\Core\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class AddressListsAddressListEntriesBulkPostBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === \KatapultAPI\Core\Model\AddressListsAddressListEntriesBulkPostBody::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \KatapultAPI\Core\Model\AddressListsAddressListEntriesBulkPostBody::class;
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \KatapultAPI\Core\Model\AddressListsAddressListEntriesBulkPostBody();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('address_list', $data)) {
                $object->setAddressList($this->denormalizer->denormalize($data['address_list'], \KatapultAPI\Core\Model\AddressListLookup::class, 'json', $context));
                unset($data['address_list']);
            }
            if (\array_key_exists('add', $data)) {
                $values = [];
                foreach ($data['add'] as $value) {
                    $values[] = $this->denormalizer->denormalize($value, \KatapultAPI\Core\Model\AddressListEntryArguments::class, 'json', $context);
                }
                $object->setAdd($values);
                unset($data['add']);
            }
            if (\array_key_exists('remove', $data)) {
                $values_1 = [];
                foreach ($data['remove'] as $value_1) {
                    $values_1[] = $this->denormalizer->denormalize($value_1, \KatapultAPI\Core\Model\AddressListEntryArguments::class, 'json', $context);
                }
                $object->setRemove($values_1);
                unset($data['remove']);
            }
            foreach ($data as $key => $value_2) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value_2;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            $data['address_list'] = $this->normalizer->normalize($object->getAddressList(), 'json', $context);
            if ($object->isInitialized('add') && null !== $object->getAdd()) {
                $values = [];
                foreach ($object->getAdd() as $value) {
                    $values[] = $this->normalizer->normalize($value, 'json', $context);
                }
                $data['add'] = $values;
            }
            if ($object->isInitialized('remove') && null !== $object->getRemove()) {
                $values_1 = [];
                foreach ($object->getRemove() as $value_1) {
                    $values_1[] = $this->normalizer->normalize($value_1, 'json', $context);
                }
                $data['remove'] = $values_1;
            }
            foreach ($object as $key => $value_2) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value_2;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\KatapultAPI\Core\Model\AddressListsAddressListEntriesBulkPostBody::class => false];
        }
    }
} else {
    class AddressListsAddressListEntriesBulkPostBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === \KatapultAPI\Core\Model\AddressListsAddressListEntriesBulkPostBody::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \KatapultAPI\Core\Model\AddressListsAddressListEntriesBulkPostBody::class;
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \KatapultAPI\Core\Model\AddressListsAddressListEntriesBulkPostBody();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('address_list', $data)) {
                $object->setAddressList($this->denormalizer->denormalize($data['address_list'], \KatapultAPI\Core\Model\AddressListLookup::class, 'json', $context));
                unset($data['address_list']);
            }
            if (\array_key_exists('add', $data)) {
                $values = [];
                foreach ($data['add'] as $value) {
                    $values[] = $this->denormalizer->denormalize($value, \KatapultAPI\Core\Model\AddressListEntryArguments::class, 'json', $context);
                }
                $object->setAdd($values);
                unset($data['add']);
            }
            if (\array_key_exists('remove', $data)) {
                $values_1 = [];
                foreach ($data['remove'] as $value_1) {
                    $values_1[] = $this->denormalizer->denormalize($value_1, \KatapultAPI\Core\Model\AddressListEntryArguments::class, 'json', $context);
                }
                $object->setRemove($values_1);
                unset($data['remove']);
            }
            foreach ($data as $key => $value_2) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value_2;
                }
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            $data['address_list'] = $this->normalizer->normalize($object->getAddressList(), 'json', $context);
            if ($object->isInitialized('add') && null !== $object->getAdd()) {
                $values = [];
                foreach ($object->getAdd() as $value) {
                    $values[] = $this->normalizer->normalize($value, 'json', $context);
                }
                $data['add'] = $values;
            }
            if ($object->isInitialized('remove') && null !== $object->getRemove()) {
                $values_1 = [];
                foreach ($object->getRemove() as $value_1) {
                    $values_1[] = $this->normalizer->normalize($value_1, 'json', $context);
                }
                $data['remove'] = $values_1;
            }
            foreach ($object as $key => $value_2) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value_2;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\KatapultAPI\Core\Model\AddressListsAddressListEntriesBulkPostBody::class => false];
        }
    }
}
