<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Exception;

class DeleteSshKeyNotFoundException extends NotFoundException
{
    /**
     * @var \Krystal\Katapult\KatapultAPI\Model\ResponseSSHKeyNotFoundResponse
     */
    private $responseSSHKeyNotFoundResponse;
    /**
     * @var \Psr\Http\Message\ResponseInterface
     */
    private $response;

    public function __construct(\Krystal\Katapult\KatapultAPI\Model\ResponseSSHKeyNotFoundResponse $responseSSHKeyNotFoundResponse, \Psr\Http\Message\ResponseInterface $response)
    {
        parent::__construct('No SSH key was found matching any of the criteria provided in the arguments');
        $this->responseSSHKeyNotFoundResponse = $responseSSHKeyNotFoundResponse;
        $this->response = $response;
    }

    public function getResponseSSHKeyNotFoundResponse(): \Krystal\Katapult\KatapultAPI\Model\ResponseSSHKeyNotFoundResponse
    {
        return $this->responseSSHKeyNotFoundResponse;
    }

    public function getResponse(): \Psr\Http\Message\ResponseInterface
    {
        return $this->response;
    }
}
