<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Krystal\Katapult\KatapultAPI\Exception;

class PatchVirtualMachineNetworkInterfaceUpdateSpeedProfileUnprocessableEntityException extends UnprocessableEntityException
{
    /**
     * @var \Krystal\Katapult\KatapultAPI\Model\ResponseSpeedProfileAlreadyAssignedResponse
     */
    private $responseSpeedProfileAlreadyAssignedResponse;
    /**
     * @var \Psr\Http\Message\ResponseInterface
     */
    private $response;

    public function __construct(\Krystal\Katapult\KatapultAPI\Model\ResponseSpeedProfileAlreadyAssignedResponse $responseSpeedProfileAlreadyAssignedResponse, \Psr\Http\Message\ResponseInterface $response)
    {
        parent::__construct('This network speed profile is already assigned to this virtual machine network interface.');
        $this->responseSpeedProfileAlreadyAssignedResponse = $responseSpeedProfileAlreadyAssignedResponse;
        $this->response = $response;
    }

    public function getResponseSpeedProfileAlreadyAssignedResponse(): \Krystal\Katapult\KatapultAPI\Model\ResponseSpeedProfileAlreadyAssignedResponse
    {
        return $this->responseSpeedProfileAlreadyAssignedResponse;
    }

    public function getResponse(): \Psr\Http\Message\ResponseInterface
    {
        return $this->response;
    }
}
