<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace KatapultAPI\Public\Model;

class SignupsPostResponse200 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The ID of the signup.
     *
     * @var string
     */
    protected $id;
    /**
     * The e-mail address that was sent the welcome email.
     *
     * @var string|null
     */
    protected $emailAddress;
    /**
     * The URL for the user to continue their signup process, only available if verify_with_email is false.
     *
     * @var string|null
     */
    protected $url;

    /**
     * The ID of the signup.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * The ID of the signup.
     */
    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    /**
     * The e-mail address that was sent the welcome email.
     */
    public function getEmailAddress(): ?string
    {
        return $this->emailAddress;
    }

    /**
     * The e-mail address that was sent the welcome email.
     */
    public function setEmailAddress(?string $emailAddress): self
    {
        $this->initialized['emailAddress'] = true;
        $this->emailAddress = $emailAddress;

        return $this;
    }

    /**
     * The URL for the user to continue their signup process, only available if verify_with_email is false.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * The URL for the user to continue their signup process, only available if verify_with_email is false.
     */
    public function setUrl(?string $url): self
    {
        $this->initialized['url'] = true;
        $this->url = $url;

        return $this;
    }
}
