name: Build PHP client

on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  # On the main branch we want all builds to complete, even if new commits are merged.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.run_id) || format('ci-{0}-ci', github.ref) }}
  cancel-in-progress: true

jobs:
  build-php:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate our client
        run: make build

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
